# To run this playbook on Debian minimal, you must do the following first:
# 1) setup sudo: 
#	$ su
#	$ apt install sudo
#	$ /usr/sbin/adduser <user> sudo
#	$ reboot
# 2) Install ansible and python dependencies:
#	$ sudo apt install -y python3 python3-pip python3-apt
#	$ sudo pip3 install ansible
# Then, to run the playbook, do:
#	$ ansible-playbook <debian_playbook.yml> --ask-become-pass>

- name: "Debian minimal workstation playbook"
  hosts: 127.0.0.1 
  connection: local
  tasks:
    - name: Install custom rice dependencies
      become: yes
      become_method: enable
      apt:
        update_cache: yes
        name:
          - awesome
          - xinit
          - rofi
          - compton
          - zsh
          - fonts-noto
          - fonts-noto-extra
          - fonts-roboto
          - fonts-powerline
          - papirus-icon-theme
          - lxappearance
          - lxterminal
          - xsettingsd
          - tmux
          - git
          - feh
          - xterm
          - rxvt-unicode
          - network-manager-gnome
          - network-manager-openvpn-gnome
          - xscreensaver
          - pasystray

    - name: Install development tools
      become: yes
      become_method: enable
      apt:
        name:
          - git
          - vim
          - vim-nox
          - vim-python
          - codeblocks
          - geany
          - tiled
          - python3
          - python3-pip
          - python3-jedi
          - cmake
          - ctags
          - mono-complete
          - build-essential

    - name: Install software suite
      become: yes
      become_method: enable
      apt:
        name:
          - xarchiver
          - firefox-esr
          - thunderbird
          - keepassxc
          - transmission
          - libreoffice
          - ranger
          - thunar
          - weechat
          - grafx2
          - milkytracker

    - name: Install dotfiles
      shell: cd ~ && git clone https://github.com/matthewspangler/dotfiles && cd dotfiles && ./install

    - name: Setup vim by running PlugInstall
      shell: vim  +PlugInstall +qall

    - name: Build youcompleteme
      shell: cd ~/.vim/plugged/youcompleteme/ && python3 install.py --clang-completer --cs-completer

    - name: Setup zsh to be default shell
      shell: chsh -s $(which zsh)

    - name: Install pywal and pywpg
      become: yes
      become_method: enable
      shell: pip3 install pywal wpgtk

    - name: Install NordVPN repository
      become: yes
      become_method: enable
      shell: wget -qnc https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb && sudo dpkg -i ./Downloads/nordvpn-release_1.0.0_all.deb

    - name: Install NordVPN client
      become: yes
      become_method: enable
      apt:
        update_cache: yes
        name:
          - nordvpn

    - name: Run pywal and pywpg
      shell: ~/set_background.sh ~/Pictures/Backgrounds/default.jpg

    - name: Merge Xresources
      shell: xrdb -merge ./Xresources

    - name: Add non-free repository
      shell:

    - name: Install steam
      become: yes
      become_method: enable
      shell: dpkg --add-architecture i386
      apt:
        update_cache: yes
        name:
          steam
